name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'  # atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false             # remove o título
          SHOW_TIME: true               # mantém tempo por linguagem
          SHOW_TOTAL: false             # remove tempo total
          TIME_RANGE: all_time
          LANG_COUNT: 6                 # mostra só as 6 linguagens mais usadas
          BLOCKS: ░▒▓█                  # blocos visuais
          STOP_AT_OTHER: true          # para no "Other", não mostra além
