name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          SHOW_TIME: true
          SHOW_TOTAL: false
          TIME_RANGE: all_time
          LANG_COUNT: 6
          BLOCKS: ░▒▓█
          STOP_AT_OTHER: false      # ← ESSA LINHA É A CHAVE
